#!/bin/bash
python train.py --dataroot /home/ypj/dataset/cholec80_desmoking/psv2rs/light --name Pix2pixSwinunetLight --model pix2pix --netG swinunet --netD basic --direction AtoB --dataset_mode aligned --norm batch --token_projection conv --embed_dim 64 --ndf 64 --ngf 64
python train.py --dataroot /home/ypj/dataset/cholec80_desmoking/psv2rs/light --name Cycle_ganSwinunetLight --model cycle_gan --netG swinunet --netD basic --direction AtoB --dataset_mode aligned --norm batch --token_projection conv --embed_dim 64 --ndf 64 --ngf 64
python train.py --dataroot /home/ypj/dataset/cholec80_desmoking/psv2rs/light --name Atmosphere_pix2pixSwinunetLight --model atmosphere_pix2pix --netG swinunet --netD basic --direction AtoB --dataset_mode aligned --norm batch --token_projection conv --embed_dim 64 --ndf 64 --ngf 64
python train.py --dataroot /home/ypj/dataset/cholec80_desmoking/psv2rs/light --name Atmosphere_cycle_ganSwinunetLight --model atmosphere_cycle_gan --netG swinunet --netD basic --direction AtoB --dataset_mode aligned --norm batch --token_projection conv --embed_dim 64 --ndf 64 --ngf 64
python train.py --dataroot /home/ypj/dataset/cholec80_desmoking/psv2rs/middle --name Pix2pixSwinunetMiddle --model pix2pix --netG swinunet --netD basic --direction AtoB --dataset_mode aligned --norm batch --token_projection conv --embed_dim 64 --ndf 64 --ngf 64
python train.py --dataroot /home/ypj/dataset/cholec80_desmoking/psv2rs/middle --name Cycle_ganSwinunetMiddle --model cycle_gan --netG swinunet --netD basic --direction AtoB --dataset_mode aligned --norm batch --token_projection conv --embed_dim 64 --ndf 64 --ngf 64
python train.py --dataroot /home/ypj/dataset/cholec80_desmoking/psv2rs/middle --name Atmosphere_pix2pixSwinunetMiddle --model atmosphere_pix2pix --netG swinunet --netD basic --direction AtoB --dataset_mode aligned --norm batch --token_projection conv --embed_dim 64 --ndf 64 --ngf 64
python train.py --dataroot /home/ypj/dataset/cholec80_desmoking/psv2rs/middle --name Atmosphere_cycle_ganSwinunetMiddle --model atmosphere_cycle_gan --netG swinunet --netD basic --direction AtoB --dataset_mode aligned --norm batch --token_projection conv --embed_dim 64 --ndf 64 --ngf 64
python train.py --dataroot /home/ypj/dataset/cholec80_desmoking/psv2rs/heavy --name Pix2pixSwinunetHeavy --model pix2pix --netG swinunet --netD basic --direction AtoB --dataset_mode aligned --norm batch --token_projection conv --embed_dim 64 --ndf 64 --ngf 64
python train.py --dataroot /home/ypj/dataset/cholec80_desmoking/psv2rs/heavy --name Cycle_ganSwinunetHeavy --model cycle_gan --netG swinunet --netD basic --direction AtoB --dataset_mode aligned --norm batch --token_projection conv --embed_dim 64 --ndf 64 --ngf 64
python train.py --dataroot /home/ypj/dataset/cholec80_desmoking/psv2rs/heavy --name Atmosphere_pix2pixSwinunetHeavy --model atmosphere_pix2pix --netG swinunet --netD basic --direction AtoB --dataset_mode aligned --norm batch --token_projection conv --embed_dim 64 --ndf 64 --ngf 64
python train.py --dataroot /home/ypj/dataset/cholec80_desmoking/psv2rs/heavy --name Atmosphere_cycle_ganSwinunetHeavy --model atmosphere_cycle_gan --netG swinunet --netD basic --direction AtoB --dataset_mode aligned --norm batch --token_projection conv --embed_dim 64 --ndf 64 --ngf 64
